### ISSUE TITLE
What does * EVERYTHING * Mean in the examples?

### ISSUE THREAD

**Issue by IkeVoodoo** [sl-lang/sll#45]
I don't understand anything about the examples, why is it so weird of a language?

**Comment by krzem5** [comment]
The `example/` directory is a directory for files used as examples for developement ofthe language. They are not intended to be the most readable nor the most efficient. Most of the code has been added just to test/debug a feature of SLL.
TL;DR it is only used to debug internal code

**Comment by krzem5** [comment]
I am planning on writing tests (#8), which would eliminate the need for the `example/` directory.

**Comment by IkeVoodoo** [comment]
Like, why is the syntax so unreadable?

**Comment by krzem5** [comment]
The languge has no keywords, only operators

**Comment by IkeVoodoo** [comment]
Its still confusing, also what's the goal of the language

**Comment by krzem5** [comment]
I did not like the fatc that you could not define a variable named `while`, so I have created this language.

**Comment by krzem5** [comment]
And also because I had nothing to do one weekend.

**Comment by IkeVoodoo** [comment]
Okay....

**Comment by IkeVoodoo** [comment]
The thing is, how do you even define a variable? it just looks like a bunch of characters tbh

**Comment by krzem5** [comment]
`(= |# insert name here #| |# value #|)`
 
or declare it (= initialize to `nil`)

`(# |# insert name here #|)`

**Comment by krzem5** [comment]
I have currently written synatx highlight for Sublie Text 4 only, however contribution to other editors (like vim) are welcome.

**Comment by IkeVoodoo** [comment]
I mean this language is kind of weird in my point of view, but if it's what you like ig

**Comment by krzem5** [comment]
I can agree, that the combination of the lisp-like syntax and the absence of keywords does not help with learning this language.

**Comment by IkeVoodoo** [comment]
i don't mean learning the language, the whole point of it and the syntax is weird, but i am not gonna judge you

**Comment by krzem5** [comment]
The language has been started when I had nothing to work on during a weekend and since them it has evolved into this. And the syntax is quite hard to learn.
